### ISSUE TITLE
Write down notes from general meeting on a text file

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist-proposalmaking#3]
For supporting issue #2

**Comment by jamesholston** [comment]
Notes are in [google doc](https://drive.google.com/open?id=1F8Npb3hJvEXbJiq68tKZ9p293vDVbJD402RcY-9aFOw&authuser=0)

**Comment by jamesholston** [comment]
The link to the notes made by the team are missing

**Comment by cdparra** [comment]
No longer needed
